### ISSUE TITLE
run error

### ISSUE THREAD

**Issue by yongcaiwang** [goncalo120/3DRegNet#1]
I run "python3 main.py --log_dir=", but I get the following error. How to fix it? 

~/3DRegNet-master/transformations.py:1900: UserWarning: failed to import module _transformations
  warnings.warn("failed to import module %s" % name)
Traceback (most recent call last):
  File "main.py", line 40, in <module>
    config, unparsed = get_config()
  File "/home/ubuntu/3DRegNet-master/config.py", line 186, in get_config
    getattr(config, "data_" + _mode))
  File "/home/ubuntu/3DRegNet-master/config.py", line 174, in setup_dataset
    assert data_dir
AssertionError

**Comment by goncalo120** [comment]
It seems that you are not giving any name to your log_dir. 

Please run for testing with the given weights:
python3 main.py --log_dir=3dregnet --run_mode=test

or if you want to train it:
python3 main.py --log_dir=[NAME]

where [NAME] is a name that you want to give to the configuration. This will create a directory in logs with the saved checkpoints.

**Comment by dansontong** [comment]
actually, I have tried 
"python3 main.py --log_dir=logs"
"python3 main.py --log_dir=3dregnet"
"python3 main.py --log_dir=/.../logs"
"python3 main.py --log_dir=/.../logs/3dregnet" # including whether 3dregnet file is exist or not

But I still get the same error.

**Comment by goncalo120** [comment]
Can you send me the the directory path of your data folder and log folder?

**Comment by mordecaimalignatius** [comment]
> I run "python3 main.py --log_dir=", but I get the following error. How to fix it?
> 
> ~/3DRegNet-master/transformations.py:1900: UserWarning: failed to import module _transformations warnings.warn("failed to import module %s" % name) Traceback (most recent call last): File "main.py", line 40, in config, unparsed = get_config() File "/home/ubuntu/3DRegNet-master/config.py", line 186, in get_config getattr(config, "data_" + _mode))
> File "/home/ubuntu/3DRegNet-master/config.py", line 174, in setup_dataset
> assert data_dir
> AssertionError

I get the same Error.
There seems to be an issue with setup_dataset():
line 174, "assert data_dir" makes sure that the list will not be empty, which will be only the case if the name is 'sun3d'.
yet for validation (dataset_name = 'data_va') the standard config string will be 'livingroom1.livingroom2.office1.office2', none of the names is 'sun3d' so this test will always fail. hence the error

**Comment by goncalo120** [comment]
@yongcaiwang  and @dansontong  please change the data_va in the config.py to sun3d and it will fix the error.

Thanks for noticing @mordecaimalignatius. I couldn't replicate the exact error.

**Comment by dansontong** [comment]
thanks very much  @mordecaimalignatius @goncalo120, it fixed the error after change 'livingroom1.livingroom2.office1.office2' to 'sun3d'.

**Comment by goncalo120** [comment]
Thanks and I already pushed the fix.
