### ISSUE TITLE
how to visualize the results

### ISSUE THREAD

**Issue by CaiStark** [goncalo120/3DRegNet#2]
I run "python3 main.py ", and I get the following result. How to visualize the results with point cloud. Just like as shown at the end of your paper.
“Total Loss error - 3.3390591144561768
Accuracies - 0.7749275726338463
Mean delta - 0.022301021782127586
Idx min: 331    Rot_min = 0.18351529710032302”

**Comment by goncalo120** [comment]
We used open3d to visualize our results. We do not provide the scripts for visualization.
