### ISSUE TITLE
Data augmentation

### ISSUE THREAD

**Issue by zgojcic** [goncalo120/3DRegNet#3]
Hi, 

is there a special reason that you only augment the data up to 50 degree rotations around only one axis? 

Do you have any information how the model performs if there are rotations around all axes and larger than 50 degrees?

Thanks

**Comment by goncalo120** [comment]
Hi!
Our data augmentation is performed across all axis. We choose an angle and a random axis (3-dim vector) to disturb the initial points. During each epoch, the angle never changes, but the axis are drawn randomly for each example. 

We tested with various angles, and 50deg generalized well and we could implement our method for the data augmentation but we could have larger or smaller rotations.

**Comment by zgojcic** [comment]
I forgot that I have never closed this issue, thank you for the answer.
